version: "3.7"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - ./server/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: "80"
    ports:
      - "80:80"

volumes:
  pgdata:
  pgadmin-data:
