import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import PageLink from "../../components/admin/PageLink";

export default function Dashboard() {
  const links = [
    { title: "Home", url: "/admin/home/heroimages" },
    { title: "Home", url: "/admin/home/heroimages" },
    { title: "Home", url: "/admin/home/heroimages" },
    { title: "Home", url: "/admin/home/heroimages" },
    { title: "Home", url: "/admin/home/heroimages" },
    { title: "Home", url: "/admin/home/heroimages" },
    { title: "Home", url: "/admin/home/heroimages" },
    { title: "Home", url: "/admin/home/heroimages" },
    { title: "Home", url: "/admin/home/heroimages" },
    { title: "Home", url: "/admin/home/heroimages" },
    { title: "Home", url: "/admin/home/heroimages" },
  ];

  return (
    <div className="main-container w-11/12 mx-auto">
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="home w-full flex flex-col justify-center">
        <h3 className="text-3xl font-bold my-10 w-full flex justify-center">
          Home
        </h3>
        <div className="home-links w-full grid-small sm:grid-medium lg:grid-large">
          <Link
            href="/admin/home/heroimages"
            className="link-card-small md:link-card hover:link-card-hover card-shadow flex justify-center items-center"
          >
            Add Images
          </Link>
          <Link
            href="/admin/home/metrics"
            className="link-card-small md:link-card hover:link-card-hover card-shadow flex justify-center items-center"
          >
            Metrics
          </Link>
          <Link
            href="/admin/home/programs"
            className="link-card-small md:link-card hover:link-card-hover card-shadow flex justify-center items-center"
          >
            Programs
          </Link>
        </div>
      </div>
      <br />
      <hr />
      <br />
      <div className="other-links grid-small sm:grid-medium lg:grid-large mb-10">
        {links.map((link) => (
          <Link
            href={link.url}
            className="link-card-small md:link-card hover:link-card-hover flex justify-center items-center card-shadow"
          >
            <PageLink title={link.title} />
          </Link>
        ))}
      </div>
    </div>
  );
}
