import Head from "next/head";

export default function Home() {
  return (
    <div className="flex justify-center items-center w-full h-screen">
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form action="" className="flex flex-col max-w-[20em]">
        <div className="username">
          <label htmlFor="username" className="font-inter">
            Username:
          </label>
          <br />
          <input
            type="text"
            id="username"
            name="username"
            className="border-2"
          />
        </div>
        <div className="password">
          <label htmlFor="password" className="font-inter">
            Password:
          </label>
          <br />
          <input
            type="password"
            id="password"
            name="username"
            className="border-2"
          />
        </div>
        <br />
        <button type="submit" className="border-2 border-red">
          Log in
        </button>
      </form>
    </div>
  );
}
