import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form action="">
        <label htmlFor="username" className="font-inter">
          Username:
        </label>
        <input type="text" id="username" />
        <label htmlFor="password" className="font-inter">
          Password:
        </label>
        <input type="password" id="password" />
      </form>
      <Link href="/admin/dashboard">Dashboard</Link>
    </>
  );
}
